### ISSUE TITLE
Not working (Application error)

### ISSUE THREAD

**Issue by terryds** [farizrifqi/play-qris#1]
It returns "Application Error" when I try to read data from it

The QR Code:

![biolbe-qris](https://github.com/farizrifqi/play-qris/assets/11571395/844d838d-9934-441f-882c-ab92872386d9)

Recording: https://jam.dev/c/cb39d427-75ba-425a-94b4-a9e5d0780b10

**Comment by farizrifqi** [comment]
Sorry for the inconvenience when attempting to read data. I've identified the problem and have implemented a fix in the 1843b40ca7e6ea98b810ff63e2ee9e13e4999ce2.

Let me know if the issue persists and thank you for your patience and understanding.
